### ISSUE TITLE
Suggestion: templates should "be" yaml files, but allow erb template syntax

### ISSUE THREAD

**Issue by aharpervc** [veracross/consult#10]
From the readme: "Templates are ERB files, and as such can do anything ERB can do."

I think we should adjust course a little bit on this. By default, when rails loads config files they are also run through ERB, and therefore even though they a "are" yaml files, you can still do templating. I believe Consult should do the same thing; primarily for consistency (both with rails, but also with `consult.yml` which already supports ERB templating, as written) but also because `my_template.yml.erb` loses yaml syntax highlighting, which is a bummer (without extra coercion).

I think this would be a documentation-only change; just say that templates are yaml files that support erb template syntax, just like config files.

**Comment by sixfeetover** [comment]
I'm good with this change, go for it.
