### ISSUE TITLE
Supported Ruby Versions?

### ISSUE THREAD

**Issue by BrianBorge** [veracross/consult#28]
I noticed there is no information about supported ruby versions.  What are they and how should the repo be updated to include this information?

Options for updating the repo:
1. Update the README to include ruby version requirements
2. Adding a `.ruby-version` file for ruby version managers to pick up on
3. Update the ruby gem metadata to stamp out required ruby version(s) [1]

Thoughts?  I like options 1 and 3.

1: https://guides.rubygems.org/specification-reference/#required_ruby_version

**Comment by aharpervc** [comment]
I think it's reasonable to add a .ruby-version file for development. My expectation is that supported ruby versions would be driven primarily by dependencies, however I can't think of any reason to avoid `spec.required_ruby_version = '~> 2.5'` either.

**Comment by aharpervc** [comment]
We should also update the CircleCI config to test against all the versions of Ruby we decide to support.

**Comment by BrianBorge** [comment]
That's a good idea.  Can I assign these two items to myself?

**Comment by aharpervc** [comment]
> That's a good idea. Can I assign these two items to myself?

Go for it

**Comment by aharpervc** [comment]
Solved by https://github.com/veracross/consult/commit/95a03bb8fc0ee0246fe2432cff46129d86e05da8 and https://github.com/veracross/consult/pull/34
